# fn_single_line = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
